export const LIST_RESTO_STARTED = 'LIST_RESTO_STARTED';
export const LIST_RESTO_SUCCESS = 'LIST_RESTO_SUCCESS';
export const LIST_RESTO_FAILURE = 'LIST_RESTO_FAILURE';

export const ADD_RESTO_STARTED = 'ADD_RESTO_STARTED';
export const ADD_RESTO_SUCCESS = 'ADD_RESTO_SUCCESS';
export const ADD_RESTO_FAILURE = 'ADD_RESTO_FAILURE';

export const ADD_TO_COLLECTION_STARTED = 'ADD_TO_COLLECTION_STARTED';
export const ADD_TO_COLLECTION_SUCESS = 'ADD_TO_COLLECTION_SUCCESS';
export const ADD_TO_COLLECTION_FAILURE = 'ADD_TO_COLLECTION_FAILURE';